services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb:latest
    container_name: laravel_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - laravel_network
    depends_on:
      - mariadb
  
  s3:
      image: minio/minio
      container_name: laravel_s3
      ports:
        - '9000:9000'
        - '9001:9001'
      command: server /data --console-address ":9001"
      networks:
        - laravel_network
      volumes:
        - s3_data:/data
      environment:
        - MINIO_ROOT_USER=your_username
        - MINIO_ROOT_PASSWORD=your_pasword
        - MINIO_DEFAULT_BUCKETS=your_bucket_name

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

volumes:
  mariadb_data:
    driver: local

  redis_data:
    driver: local

  s3_data:
    driver: local

networks:
  laravel_network:
    driver: bridge

  minionetwork:
    driver: bridge